/**
 * Stub data for MSDC Leads API.
 * This will be replaced with real Supabase data later.
 */

import type { MsdcLead } from "@/types/leads";

export const STUB_MSDC_LEADS: MsdcLead[] = [
  {
    lead_id: "1",
    customer_name: "PT Telkom Indonesia",
    pic: "Budi Santoso",
    segment: "Telkom Group",
    channel: "Internal Referral",
    need_description: "Layanan cloud infrastructure untuk digitalisasi operasional",
    tender_name: "Tender Cloud Infrastructure 2025",
    project_value_m: 15.5,
    status_tender: "Open",
    created_at: "2025-01-15T08:00:00Z",
  },
  {
    lead_id: "2",
    customer_name: "Bank Mandiri",
    pic: "Siti Nurhaliza",
    segment: "Private",
    channel: "Marketing Campaign",
    need_description: "Sistem payment gateway untuk e-banking platform",
    tender_name: "Payment Gateway Implementation",
    project_value_m: 8.2,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-10T09:30:00Z",
  },
  {
    lead_id: "3",
    customer_name: "PT Pertamina",
    pic: "Ahmad Yani",
    segment: "SOE",
    channel: "Partnership",
    need_description: "Platform manajemen supply chain untuk operasi distribusi",
    tender_name: "Supply Chain Management System",
    project_value_m: 22.8,
    status_tender: "Open",
    created_at: "2025-01-18T10:15:00Z",
  },
  {
    lead_id: "4",
    customer_name: "Kementerian Kesehatan",
    pic: "Dr. Rina Wati",
    segment: "Gov",
    channel: "Government Procurement",
    need_description: "Sistem informasi kesehatan terintegrasi untuk puskesmas",
    tender_name: "SIK Terintegrasi Puskesmas",
    project_value_m: 12.5,
    status_tender: "Selesai",
    created_at: "2024-12-05T14:20:00Z",
  },
  {
    lead_id: "5",
    customer_name: "CV Sumber Makmur",
    pic: "Hendra Wijaya",
    segment: "SME & Reg",
    channel: "Website Inquiry",
    need_description: "Aplikasi ERP untuk manajemen inventory dan keuangan",
    tender_name: "ERP System Implementation",
    project_value_m: 2.3,
    status_tender: "Gagal",
    created_at: "2024-11-20T11:45:00Z",
  },
  {
    lead_id: "6",
    customer_name: "PT Bank Negara Indonesia",
    pic: "Rina Dewi",
    segment: "Private",
    channel: "Sales Call",
    need_description: "Layanan cybersecurity audit dan penetration testing",
    tender_name: "Cybersecurity Audit Services",
    project_value_m: 5.7,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-12T16:00:00Z",
  },
  {
    lead_id: "7",
    customer_name: "PT PLN",
    pic: "Indra Pratama",
    segment: "SOE",
    channel: "Tender Portal",
    need_description: "Platform IoT untuk monitoring jaringan distribusi listrik",
    tender_name: "IoT Smart Grid Monitoring",
    project_value_m: 18.9,
    status_tender: "Open",
    created_at: "2025-01-20T08:30:00Z",
  },
  {
    lead_id: "8",
    customer_name: "PT Garuda Indonesia",
    pic: "Lisa Wijaya",
    segment: "Private",
    channel: "Partnership",
    need_description: "Sistem reservasi dan ticketing online terbaru",
    tender_name: "Next-Gen Reservation System",
    project_value_m: 9.4,
    status_tender: "Open",
    created_at: "2025-01-14T13:15:00Z",
  },
  {
    lead_id: "9",
    customer_name: "PT Wijaya Karya",
    pic: "Bambang Sutrisno",
    segment: "SOE",
    channel: "Internal Referral",
    need_description: "Platform project management untuk konstruksi",
    tender_name: "Construction Project Management Platform",
    project_value_m: 14.6,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-08T09:00:00Z",
  },
  {
    lead_id: "10",
    customer_name: "Kementerian Pendidikan",
    pic: "Prof. Ahmad Dahlan",
    segment: "Gov",
    channel: "Government Procurement",
    need_description: "Learning Management System untuk sekolah-sekolah di Indonesia",
    tender_name: "LMS Nasional",
    project_value_m: 25.0,
    status_tender: "Selesai",
    created_at: "2024-11-15T10:00:00Z",
  },
  {
    lead_id: "11",
    customer_name: "PT Indosat",
    pic: "Maya Sari",
    segment: "Telkom Group",
    channel: "Internal Referral",
    need_description: "Platform big data analytics untuk customer insights",
    tender_name: "Customer Analytics Platform",
    project_value_m: 11.2,
    status_tender: "Open",
    created_at: "2025-01-17T15:30:00Z",
  },
  {
    lead_id: "12",
    customer_name: "PT Astra International",
    pic: "John Doe",
    segment: "Private",
    channel: "Marketing Campaign",
    need_description: "Sistem dealer management untuk jaringan showroom",
    tender_name: "Dealer Management System",
    project_value_m: 7.8,
    status_tender: "Gagal",
    created_at: "2024-10-25T12:00:00Z",
  },
  {
    lead_id: "13",
    customer_name: "PT Unilever Indonesia",
    pic: "Sarah Indira",
    segment: "Private",
    channel: "Sales Call",
    need_description: "Platform e-commerce untuk distribusi produk konsumen",
    tender_name: "E-Commerce Distribution Platform",
    project_value_m: 6.5,
    status_tender: "Open",
    created_at: "2025-01-19T11:20:00Z",
  },
  {
    lead_id: "14",
    customer_name: "PT Jasa Marga",
    pic: "Agung Prasetyo",
    segment: "SOE",
    channel: "Internal Referral",
    need_description: "Sistem toll payment elektronik terintegrasi",
    tender_name: "Electronic Toll Collection System",
    project_value_m: 19.3,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-11T14:00:00Z",
  },
  {
    lead_id: "15",
    customer_name: "PT Kereta Api Indonesia",
    pic: "Dewi Sartika",
    segment: "SOE",
    channel: "Tender Portal",
    need_description: "Platform reservasi tiket kereta api online",
    tender_name: "Online Train Reservation System",
    project_value_m: 13.7,
    status_tender: "Open",
    created_at: "2025-01-16T09:45:00Z",
  },
  {
    lead_id: "16",
    customer_name: "PT Semen Indonesia",
    pic: "Bambang Hermawan",
    segment: "SOE",
    channel: "Partnership",
    need_description: "Sistem manajemen logistik untuk distribusi semen",
    tender_name: "Cement Distribution Logistics System",
    project_value_m: 16.4,
    status_tender: "Selesai",
    created_at: "2024-11-18T15:30:00Z",
  },
  {
    lead_id: "17",
    customer_name: "PT Pupuk Indonesia",
    pic: "Indah Permata",
    segment: "SOE",
    channel: "Internal Referral",
    need_description: "Platform monitoring produksi pupuk real-time",
    tender_name: "Real-time Production Monitoring Platform",
    project_value_m: 10.8,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-09T10:00:00Z",
  },
  {
    lead_id: "18",
    customer_name: "Kementerian Perhubungan",
    pic: "Ir. Budi Santoso",
    segment: "Gov",
    channel: "Government Procurement",
    need_description: "Sistem manajemen lalu lintas terintegrasi",
    tender_name: "Integrated Traffic Management System",
    project_value_m: 28.5,
    status_tender: "Open",
    created_at: "2025-01-21T13:00:00Z",
  },
  {
    lead_id: "19",
    customer_name: "PT Freeport Indonesia",
    pic: "Michael Johnson",
    segment: "Private",
    channel: "Sales Call",
    need_description: "Platform manajemen operasi tambang terintegrasi",
    tender_name: "Integrated Mining Operations Platform",
    project_value_m: 32.1,
    status_tender: "Open",
    created_at: "2025-01-22T08:15:00Z",
  },
  {
    lead_id: "20",
    customer_name: "PT Adaro Energy",
    pic: "Bambang Setiawan",
    segment: "Private",
    channel: "Partnership",
    need_description: "Sistem monitoring lingkungan untuk operasi tambang",
    tender_name: "Environmental Monitoring System",
    project_value_m: 9.6,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-13T16:45:00Z",
  },
  {
    lead_id: "21",
    customer_name: "PT Bank Central Asia",
    pic: "Linda Sari",
    segment: "Private",
    channel: "Marketing Campaign",
    need_description: "Platform mobile banking dengan fitur canggih",
    tender_name: "Advanced Mobile Banking Platform",
    project_value_m: 14.2,
    status_tender: "Open",
    created_at: "2025-01-18T12:30:00Z",
  },
  {
    lead_id: "22",
    customer_name: "PT Sampoerna",
    pic: "Andi Wijaya",
    segment: "Private",
    channel: "Sales Call",
    need_description: "Sistem manajemen supply chain untuk distribusi rokok",
    tender_name: "Cigarette Distribution Supply Chain",
    project_value_m: 11.5,
    status_tender: "Gagal",
    created_at: "2024-10-28T10:00:00Z",
  },
  {
    lead_id: "23",
    customer_name: "PT Gudang Garam",
    pic: "Sari Indah",
    segment: "Private",
    channel: "Website Inquiry",
    need_description: "Platform e-procurement untuk pembelian bahan baku",
    tender_name: "E-Procurement Platform",
    project_value_m: 8.9,
    status_tender: "Sedang Berjalan",
    created_at: "2025-01-07T14:20:00Z",
  },
];
